// <auto-generated />
using System;
using MediBook.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediBook.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601085125_SeedDoctors")]
    partial class SeedDoctors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediBook.API.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("QueueNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MediBook.API.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=200&auto=format&fit=crop",
                            Name = "Dr. Ahmed Ali",
                            Specialty = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1594824813573-246434e33963?q=80&w=200&auto=format&fit=crop",
                            Name = "Dr. Sara Mohamed",
                            Specialty = "Cardiology"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=200&auto=format&fit=crop",
                            Name = "Dr. Mohamed Hassan",
                            Specialty = "Dermatology"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1651008376811-b90baee60c1f?q=80&w=200&auto=format&fit=crop",
                            Name = "Dr. Nour Ahmed",
                            Specialty = "Dermatology"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=200&auto=format&fit=crop",
                            Name = "Dr. Omar Khaled",
                            Specialty = "Pediatrics"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=200&auto=format&fit=crop",
                            Name = "Dr. Mona Said",
                            Specialty = "Pediatrics"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://images.unsplash.com/photo-1637059824899-a441006a6875?q=80&w=200&auto=format&fit=crop",
                            Name = "Dr. Khaled Ibrahim",
                            Specialty = "Orthopedics"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://images.unsplash.com/photo-1594824813573-246434e33963?q=80&w=200&auto=format&fit=crop",
                            Name = "Dr. Dina Mostafa",
                            Specialty = "Orthopedics"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=200&auto=format&fit=crop",
                            Name = "Dr. Youssef Adel",
                            Specialty = "Neurology"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://images.unsplash.com/photo-1651008376811-b90baee60c1f?q=80&w=200&auto=format&fit=crop",
                            Name = "Dr. Rana Tarek",
                            Specialty = "Neurology"
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=200&auto=format&fit=crop",
                            Name = "Dr. Hossam Nabil",
                            Specialty = "General"
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=200&auto=format&fit=crop",
                            Name = "Dr. Layla Hassan",
                            Specialty = "General"
                        });
                });

            modelBuilder.Entity("MediBook.API.Models.Appointment", b =>
                {
                    b.HasOne("MediBook.API.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MediBook.API.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
